services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./pyproject.toml:/app/pyproject.toml

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

    develop:
      watch:
        - action: rebuild
          path: ./pyproject.toml

    depends_on:
      - db
    environment:
      DB_NAME: mydatabase
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ./src:/app/src

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "uv", "run", "python", "src/worker/scraper_worker.py" ]
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    environment:
      DB_NAME: mydatabase
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
    
